/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface PsButton {
    'backgroundColor': string;
    'fontSize': number;
    'raised': boolean;
    'shadow': boolean;
    'text': string;
    'textColor': string;
  }
  interface PsButtonAttributes extends StencilHTMLAttributes {
    'backgroundColor'?: string;
    'fontSize'?: number;
    'raised'?: boolean;
    'shadow'?: boolean;
    'text'?: string;
    'textColor'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'PsButton': Components.PsButton;
  }

  interface StencilIntrinsicElements {
    'ps-button': Components.PsButtonAttributes;
  }


  interface HTMLPsButtonElement extends Components.PsButton, HTMLStencilElement {}
  var HTMLPsButtonElement: {
    prototype: HTMLPsButtonElement;
    new (): HTMLPsButtonElement;
  };

  interface HTMLElementTagNameMap {
    'ps-button': HTMLPsButtonElement
  }

  interface ElementTagNameMap {
    'ps-button': HTMLPsButtonElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
